version: "3"
services:
    postgresql:
        image: postgres:14.0
        container_name: lab-postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./docker/.postgresql:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        container_name: lab-redis
        command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./docker/redis/.data:/usr/local/etc/redis
